# Generated by Django 3.2.7 on 2021-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name1', models.CharField(default='udit', max_length=20)),
                ('startdate1', models.DateTimeField(blank=True, null=True)),
                ('enddate1', models.DateTimeField(blank=True, null=True)),
                ('valueindollars1', models.CharField(default='dollar', max_length=30)),
            ],
            options={
                'db_table': 'Emp',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
